name: Update Metadata
on:
 push:
   paths:
     - '**/manifest.yml'

jobs:
 update:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v2
     
     - name: Install dependencies
       run: pip install PyYAML
       
     - name: Update metadata
       run: |
         cd $GITHUB_WORKSPACE
         python .github/scripts/update_metadata.py
         
     - name: Commit changes
       run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add */metadata.json
         git commit -m "Update metadata" || exit 0
         git push
